server:
    address: 127.0.0.1
    port: 8080
    domain: # Specify domain to overwrite return IP address & port

files:
    filesPath: /files
    maxUploadSize: 20
    keyLength: 7
    allowedFileTypes:
        [
            .png,
            .jpg,
            .gif,
            .mp4,
            .mp3,
            .jpeg,
            .tiff,
            .bmp,
            .ico,
            .psd,
            .eps,
            .raw,
            .cr2,
            .nef,
            .sr2,
            .orf,
            .svg,
            .wav,
            .webm,
            .aac,
            .flac,
            .ogg,
            .wma,
            .m4a,
            .gifv,
        ]

other:
    prettyOutput: true
